Quest_Maths_E=["This is the placeholder text for question Maths 1 Easy",
               "This is the placeholder text for question Maths 2 Easy",
               "This is the placeholder text for question Maths 3 Easy",
               "This is the placeholder text for question Maths 4 Easy",
               "This is the placeholder text for question Maths 5 Easy",
               "This is the placeholder text for question Maths 6 Easy",
               "This is the placeholder text for question Maths 7 Easy",
               "This is the placeholder text for question Maths 8 Easy",
               "This is the placeholder text for question Maths 9 Easy",
               "This is the placeholder text for question Maths 10 Easy"]

Quest_Maths_M=["This is the placeholder text for question Maths 1 Medium",
               "This is the placeholder text for question Maths 2 Medium",
               "This is the placeholder text for question Maths 3 Medium",
               "This is the placeholder text for question Maths 4 Medium",
               "This is the placeholder text for question Maths 5 Medium",
               "This is the placeholder text for question Maths 6 Medium",
               "This is the placeholder text for question Maths 7 Medium",
               "This is the placeholder text for question Maths 8 Medium",
               "This is the placeholder text for question Maths 9 Medium",
               "This is the placeholder text for question Maths 10 Medium"]

Quest_Maths_H=["This is the placeholder text for question Maths 1 Hard",
               "This is the placeholder text for question Maths 2 Hard",
               "This is the placeholder text for question Maths 3 Hard",
               "This is the placeholder text for question Maths 4 Hard",
               "This is the placeholder text for question Maths 5 Hard",
               "This is the placeholder text for question Maths 6 Hard",
               "This is the placeholder text for question Maths 7 Hard",
               "This is the placeholder text for question Maths 8 Hard",
               "This is the placeholder text for question Maths 9 Hard",
               "This is the placeholder text for question Maths 10 Hard"]

Quest_CS_E=   ["This is the placeholder text for question CS 1 Easy",
               "This is the placeholder text for question CS 2 Easy",
               "This is the placeholder text for question CS 3 Easy",
               "This is the placeholder text for question CS 4 Easy",
               "This is the placeholder text for question CS 5 Easy",
               "This is the placeholder text for question CS 6 Easy",
               "This is the placeholder text for question CS 7 Easy",
               "This is the placeholder text for question CS 8 Easy",
               "This is the placeholder text for question CS 9 Easy",
               "This is the placeholder text for question CS 10 Easy"]

Quest_CS_M=   ["This is the placeholder text for question CS 1 Medium",
               "This is the placeholder text for question CS 2 Medium",
               "This is the placeholder text for question CS 3 Medium",
               "This is the placeholder text for question CS 4 Medium",
               "This is the placeholder text for question CS 5 Medium",
               "This is the placeholder text for question CS 6 Medium",
               "This is the placeholder text for question CS 7 Medium",
               "This is the placeholder text for question CS 8 Medium",
               "This is the placeholder text for question CS 9 Medium",
               "This is the placeholder text for question CS 10 Medium"]

Quest_CS_H=   ["This is the placeholder text for question CS 1 Hard",
               "This is the placeholder text for question CS 2 Hard",
               "This is the placeholder text for question CS 3 Hard",
               "This is the placeholder text for question CS 4 Hard",
               "This is the placeholder text for question CS 5 Hard",
               "This is the placeholder text for question CS 6 Hard",
               "This is the placeholder text for question CS 7 Hard",
               "This is the placeholder text for question CS 8 Hard",
               "This is the placeholder text for question CS 9 Hard",
               "This is the placeholder text for question CS 10 Hard"]

Quest_SC_E=   ["This is the placeholder text for question Science 1 Easy",
               "This is the placeholder text for question Science 2 Easy",
               "This is the placeholder text for question Science 3 Easy",
               "This is the placeholder text for question Science 4 Easy",
               "This is the placeholder text for question Science 5 Easy",
               "This is the placeholder text for question Science 6 Easy",
               "This is the placeholder text for question Science 7 Easy",
               "This is the placeholder text for question Science 8 Easy",
               "This is the placeholder text for question Science 9 Easy",
               "This is the placeholder text for question Science 10 Easy"]

Quest_SC_M=   ["This is the placeholder text for question Science 1 Medium",
               "This is the placeholder text for question Science 2 Medium",
               "This is the placeholder text for question Science 3 Medium",
               "This is the placeholder text for question Science 4 Medium",
               "This is the placeholder text for question Science 5 Medium",
               "This is the placeholder text for question Science 6 Medium",
               "This is the placeholder text for question Science 7 Medium",
               "This is the placeholder text for question Science 8 Medium",
               "This is the placeholder text for question Science 9 Medium",
               "This is the placeholder text for question Science 10 Medium"]

Quest_SC_H=   ["This is the placeholder text for question Science 1 Hard",
               "This is the placeholder text for question Science 2 Hard",
               "This is the placeholder text for question Science 3 Hard",
               "This is the placeholder text for question Science 4 Hard",
               "This is the placeholder text for question Science 5 Hard",
               "This is the placeholder text for question Science 6 Hard",
               "This is the placeholder text for question Science 7 Hard",
               "This is the placeholder text for question Science 8 Hard",
               "This is the placeholder text for question Science 9 Hard",
               "This is the placeholder text for question Science 10 Hard"]

Quest_Eg_E=   ["This is the placeholder text for question English 1 Easy",
               "This is the placeholder text for question English 2 Easy",
               "This is the placeholder text for question English 3 Easy",
               "This is the placeholder text for question English 4 Easy",
               "This is the placeholder text for question English 5 Easy",
               "This is the placeholder text for question English 6 Easy",
               "This is the placeholder text for question English 7 Easy",
               "This is the placeholder text for question English 8 Easy",
               "This is the placeholder text for question English 9 Easy",
               "This is the placeholder text for question English 10 Easy"]

Quest_Eg_M=   ["This is the placeholder text for question English 1 Medium",
               "This is the placeholder text for question English 2 Medium",
               "This is the placeholder text for question English 3 Medium",
               "This is the placeholder text for question English 4 Medium",
               "This is the placeholder text for question English 5 Medium",
               "This is the placeholder text for question English 6 Medium",
               "This is the placeholder text for question English 7 Medium",
               "This is the placeholder text for question English 8 Medium",
               "This is the placeholder text for question English 9 Medium",
               "This is the placeholder text for question English 10 Medium"]

Quest_Eg_H=   ["This is the placeholder text for question English 1 Hard",
               "This is the placeholder text for question English 2 Hard",
               "This is the placeholder text for question English 3 Hard",
               "This is the placeholder text for question English 4 Hard",
               "This is the placeholder text for question English 5 Hard",
               "This is the placeholder text for question English 6 Hard",
               "This is the placeholder text for question English 7 Hard",
               "This is the placeholder text for question English 8 Hard",
               "This is the placeholder text for question English 9 Hard",
               "This is the placeholder text for question English 10 Hard"]

Quest_GK_E=   ["This is the placeholder text for question GK 1 Easy",
               "This is the placeholder text for question GK 2 Easy",
               "This is the placeholder text for question GK 3 Easy",
               "This is the placeholder text for question GK 4 Easy",
               "This is the placeholder text for question GK 5 Easy",
               "This is the placeholder text for question GK 6 Easy",
               "This is the placeholder text for question GK 7 Easy",
               "This is the placeholder text for question GK 8 Easy",
               "This is the placeholder text for question GK 9 Easy",
               "This is the placeholder text for question GK 10 Easy"]

Quest_GK_M=   ["This is the placeholder text for question GK 1 Medium",
               "This is the placeholder text for question GK 2 Medium",
               "This is the placeholder text for question GK 3 Medium",
               "This is the placeholder text for question GK 4 Medium",
               "This is the placeholder text for question GK 5 Medium",
               "This is the placeholder text for question GK 6 Medium",
               "This is the placeholder text for question GK 7 Medium",
               "This is the placeholder text for question GK 8 Medium",
               "This is the placeholder text for question GK 9 Medium",
               "This is the placeholder text for question GK 10 Medium"]

Quest_GK_H=   ["This is the placeholder text for question GK 1 Hard",
               "This is the placeholder text for question GK 2 Hard",
               "This is the placeholder text for question GK 3 Hard",
               "This is the placeholder text for question GK 4 Hard",
               "This is the placeholder text for question GK 5 Hard",
               "This is the placeholder text for question GK 6 Hard",
               "This is the placeholder text for question GK 7 Hard",
               "This is the placeholder text for question GK 8 Hard",
               "This is the placeholder text for question GK 9 Hard",
               "This is the placeholder text for question GK 10 Hard"]

Opt_Maths_E=[["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"]]

Opt_Maths_M=[["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"]]

Opt_Maths_H=[["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"]]

Opt_CS_E=   [["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"]]

Opt_CS_M=   [["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"]]

Opt_CS_H=   [["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"]]

Opt_Sc_E=   [["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"]]

Opt_Sc_M=   [["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"]]

Opt_Sc_H=   [["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"]]

Opt_Eg_E=   [["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"]]

Opt_Eg_M=   [["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"]]

Opt_Eg_H=   [["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"]]

Opt_GK_E=   [["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"]]

Opt_GK_M=   [["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"]]

Opt_GK_H=   [["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"],
             ["Option 1 Placeholder","Option 2 Placeholder","Option 3 Placeholder","Option 4 Placeholder"]]

Ans_Maths_E=["A",
             "B",
             "C",
             "D",
             "A",
             "B",
             "C",
             "D",
             "A",
             "B"]

Ans_Maths_M=["A",
             "B",
             "C",
             "D",
             "A",
             "B",
             "C",
             "D",
             "A",
             "B"]

Ans_Maths_H=["A",
             "B",
             "C",
             "D",
             "A",
             "B",
             "C",
             "D",
             "A",
             "B"]

Ans_CS_E=   ["A",
             "B",
             "C",
             "D",
             "A",
             "B",
             "C",
             "D",
             "A",
             "B"]

Ans_CS_M=   ["A",
             "B",
             "C",
             "D",
             "A",
             "B",
             "C",
             "D",
             "A",
             "B"]

Ans_CS_H=   ["A",
             "B",
             "C",
             "D",
             "A",
             "B",
             "C",
             "D",
             "A",
             "B"]

Ans_Sc_E=   ["A",
             "B",
             "C",
             "D",
             "A",
             "B",
             "C",
             "D",
             "A",
             "B"]

Ans_Sc_M=   ["A",
             "B",
             "C",
             "D",
             "A",
             "B",
             "C",
             "D",
             "A",
             "B"]

Ans_Sc_H=   ["A",
             "B",
             "C",
             "D",
             "A",
             "B",
             "C",
             "D",
             "A",
             "B"]

Ans_Eg_E=   ["A",
             "B",
             "C",
             "D",
             "A",
             "B",
             "C",
             "D",
             "A",
             "B"]

Ans_Eg_M=   ["A",
             "B",
             "C",
             "D",
             "A",
             "B",
             "C",
             "D",
             "A",
             "B"]

Ans_Eg_H=   ["A",
             "B",
             "C",
             "D",
             "A",
             "B",
             "C",
             "D",
             "A",
             "B"]

Ans_GK_E=   ["A",
             "B",
             "C",
             "D",
             "A",
             "B",
             "C",
             "D",
             "A",
             "B"]

Ans_GK_M=   ["A",
             "B",
             "C",
             "D",
             "A",
             "B",
             "C",
             "D",
             "A",
             "B"]

Ans_GK_H=   ["A",
             "B",
             "C",
             "D",
             "A",
             "B",
             "C",
             "D",
             "A",
             "B"]

Wr_Ans_Maths_E=[["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"]]

Wr_Ans_Maths_M=[["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"]]

Wr_Ans_Maths_H=[["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"]]

Wr_Ans_CS_E=   [["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"]]

Wr_Ans_CS_M=   [["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"]]

Wr_Ans_CS_H=   [["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"]]

Wr_Ans_Sc_E=   [["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"]]

Wr_Ans_Sc_M=   [["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"]]

Wr_Ans_Sc_H=   [["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"]]

Wr_Ans_Eg_E=   [["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"]]

Wr_Ans_Eg_M=   [["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"]]

Wr_Ans_Eg_H=   [["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"]]

Wr_Ans_GK_E=   [["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"]]

Wr_Ans_GK_M=   [["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"]]

Wr_Ans_GK_H=   [["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"],
                ["A","B","D"],
                ["A","B","C"],
                ["B","C","D"],
                ["A","C","D"]]
